image: node:12.14.1

stages:
  - build
  - deploy

release:
  stage: build
  script:
    - npm i --non-interactive --pure-lockfile
    - npm run build
    - npm run release -- patch --ci --verbose

deploy:
  stage: deploy
  script:
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
